### ISSUE TITLE
EV Smart charging kills charging everywhere.

### ISSUE THREAD

**Issue by Dominic-070** [jonasbkarlsson/ev_smart_charging#154]
EV Smart charging stops charging everywhere.

Since update 1.7.0 charging is stopped everywhere.

Normally `EV Smart charging` integration only affects the charging switch if the `vehicle connected` switch is on.

Now when I'm at work or somewhere else than home, and I connect the plug to the car, the car starts charging briefly and the charger switch of the `Tesla integration` is immediately switched off again by the `EV Smart charging` integration.

It seems that the `vehicle connected` switch of the `EV Smart charging` integration is completely ignored.

**Debug log:**
2023-03-07 14:03:55.364 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 10 Interval 60
2023-03-07 14:03:55.364 DEBUG (MainThread) [teslajsonpy.controller] 36298: online. Polling policy: normal. Update state: normal. Since last park: 4021.4210000038147. Since last wake up: 50626. Idle interval: 600. shift_state: None sentry: True climate: False, charging: Stopped 
2023-03-07 14:03:55.364 DEBUG (MainThread) [teslajsonpy.controller] 36298: Skipping update with state online. Polling: True. Last update: 519 ago. Last parked: 4021.4210000038147 ago. Last wake up 50626 ago. 
2023-03-07 14:03:56.916 DEBUG (MainThread) [teslajsonpy.car] Sending command: START_CHARGE
2023-03-07 14:03:56.917 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 3:53:27
2023-03-07 14:03:56.917 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/vehicles/XXXXXXXXXXXXXXXX/command/charge_start {}
2023-03-07 14:03:57.201 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"reason":"is_charging","result":false}}
2023-03-07 14:03:57.202 DEBUG (MainThread) [teslajsonpy.car] Response from command START_CHARGE: {'response': {'reason': 'is_charging', 'result': False}}
2023-03-07 14:04:05.365 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 20 Interval 60
2023-03-07 14:04:05.366 DEBUG (MainThread) [teslajsonpy.controller] 36298: online. Polling policy: normal. Update state: normal. Since last park: 4031.4210000038147. Since last wake up: 50636. Idle interval: 600. shift_state: None sentry: True climate: False, charging: Stopped 
2023-03-07 14:04:05.366 DEBUG (MainThread) [teslajsonpy.controller] 36298: Skipping update with state online. Polling: True. Last update: 529 ago. Last parked: 4031.4210000038147 ago. Last wake up 50636 ago. 
2023-03-07 14:04:10.643 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1191, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1170, in sendfile
    return await self._sendfile_fallback(transport, file,
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1200, in _sendfile_fallback
    await proto.restore()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 268, in restore
    self._transport.resume_reading()
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'

**Settings:**
![image](https://user-images.githubusercontent.com/62623885/223425605-b3e9476f-654a-44f6-ae80-662654c73522.png)
![image](https://user-images.githubusercontent.com/62623885/223431293-73fb0684-1071-4195-a673-a8695e4613b7.png)

**Comment by jonasbkarlsson** [comment]
Hi! Did your problem happen at 14:03:55?

Is the automation "EV Smart Charging - EV connected" used to control the `switch.ev_smart_charging_ev_connected`?

If you in your second screen shot click on "Toon meer", and then add the entity `switch.ev_smart_charging_ev_connected`, how does it look like during this time (From 21:00 March 6th and 1500 March 7th)?
