### ISSUE TITLE
could not convert string to float: 'unavailable'

### ISSUE THREAD

**Issue by woopstar** [jonasbkarlsson/ev_smart_charging#328]
Sometimes, some of the sensors become unavailable. This results in the following error in the log:

```
2024-09-23 09:09:33.136 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/ev_smart_charging/coordinator.py", line 770, in update_sensors_new
    await self.update_sensors(
  File "/config/custom_components/ev_smart_charging/coordinator.py", line 820, in update_sensors
    self.solar_charging.update_grid_usage(float(new_state.state))
                                          ^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'
```

There should be a check for this in the code.

**Comment by proscar87** [comment]
This looks already resolved in `main`. The traceback comes from `SolarCharging.update_grid_usage(float(new_state.state))`, and that whole code path was removed in `3f19eac` ("Revert 'Solar power based charging.'", Jan 2025), which is in `main` since v2.3.0 — `solar_charging` / `update_grid_usage` no longer exist anywhere in the component.

For what it's worth, I also checked the remaining state-to-float conversions on current `main`: the SOC ones in `coordinator.py` go through `Validator.is_soc_state()` and the `config_flow` helpers through `Validator.is_float()`, both of which reject `unavailable`/`unknown` (there's an existing regression test for exactly that in `tests/helpers/test_general.py`). So I couldn't find any remaining unguarded occurrence of this pattern.

Probably safe to close.
