### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by achmeed** [jonasbkarlsson/ev_smart_charging#42]
When trying to add the plugin in Hass following error appears and the installation fails:

Unexpected exception importing platform custom_components.ev_smart_charging.config_flow

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/ev_smart_charging/__init__.py", line 10, in <module>
    from .coordinator import EVSmartChargingCoordinator
  File "/home/homeassistant/.homeassistant/custom_components/ev_smart_charging/coordinator.py", line 26, in <module>
    from .helpers.coordinator import (
  File "/home/homeassistant/.homeassistant/custom_components/ev_smart_charging/helpers/coordinator.py", line 215, in <module>
    class Scheduler:
  File "/home/homeassistant/.homeassistant/custom_components/ev_smart_charging/helpers/coordinator.py", line 272, in Scheduler
    def get_schedule(self, params: dict[str, Any]) -> list | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by jonasbkarlsson** [comment]
Which version of Home Assistant are you using?

**Comment by jonasbkarlsson** [comment]
Error caused by Python 3.10 code. Removed by #43 to make it compatible with Python 3.9.
